### PR TITLE
work on shell

### PR DESCRIPTION
**Pull request by kweav**
Added 4 chapter `.Rmd` files and included them in `_bookdown.yml` 

Edited the course name and description in various places of `index.Rmd` and `README.md` 

Also changed the favicon to be ITN branded

### CODE REVIEW

**Comment by kweav** [comment]
The favicon appears unchanged in the preview and I think I need to remove the "why computational skills are useful" from the chapter titles. They're too long and indistinguishable in the sidebar

**Comment by kweav** [comment]
Following this info to change style: https://www.ottrproject.org/customize-style.html

**Review by carriewright11 — APPROVED** [review]
Looks great - thank you!

**Comment by howardbaik** [comment]
@kweav I restored this branch to look into https://github.com/fhdsl/bench_to_bytes/actions/runs/9303023514/job/25604848313

**Pull request merged**
